# Generated by Django 2.2.19 on 2023-06-13 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsite',
            name='site_current_date',
        ),
    ]
