# Generated by Django 2.2.19 on 2023-06-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exchangeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemodel',
            name='money',
            field=models.IntegerField(help_text='Введите денежную сумму, а мы придумаем, как её разменять!', null=True),
        ),
    ]
