# Generated by Django 2.2.19 on 2023-06-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exchangeapp', '0003_auto_20230612_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemodel',
            name='money',
            field=models.IntegerField(default=0, help_text='Введите денежную сумму, а мы придумаем, как её разменять!', unique=True),
        ),
    ]
