# Generated by Django 2.2.19 on 2023-06-13 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exchangeapp', '0004_auto_20230612_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangemodel',
            options={'ordering': ('-money',), 'verbose_name': 'Размен валюты', 'verbose_name_plural': 'Размен валюты'},
        ),
    ]
